### ISSUE TITLE
Source from a local directory.

### ISSUE THREAD

**Issue by tnordberg** [indirect/puppet-prefpane#3]
Thanks for the great tool. I'm noticing there is a regex blocking any source not starting with 'http(s)'. 

Is there a specific reason for this? In certain scenarios I may want to download the zip first, then install from a local directory.

**Comment by indirect** [comment]
If puppet:// urls work for you, I'm happy to merge a PR that allows both.

**Comment by tnordberg** [comment]
Sounds good. I'm happy to work on the pull request but must plead ignorance when it comes to using 'puppet://'. 

What I'd like to do is download a folder of zips to my machine. Once they are downloaded, use your prefpane type to install them. Is that something I can do with a 'puppet://' url?

Allowing 'file://' urls would work, or vanilla local pathing. I'm thinking there was a reason you decided to block those however, which is what I originally was curious about. 

If I changed the regex to also allow puppet:// AND file://, would that be acceptable?

**Comment by indirect** [comment]
The `puppet://` URL setup is how you handle files that are inside puppet modules. The reason I validate for `http://` is that I only wrote code to handle those urls. You'll probably need to change the code to allow either direct file paths or prefpanes that are inside puppet modules. Happy to accept a PR, though.

**Comment by tnordberg** [comment]
Thanks. I am closing because I won't have time to make the pull request in the near future but may return to it later.
